### ISSUE TITLE
Question about different kinds of MCP servers

### ISSUE THREAD

**Issue by binduwavell** [phildougherty/mcp-compose#3]
It is not clear to me if this supports HTTP+SSE and/or Stremable HTTP MCP servers?

How does this handle pre-packaged docker containers like mcp/fetch?

**Comment by binduwavell** [comment]
I tried to run the `mcp/fetch` container with this `mcp-compose.yml`:

```yaml
version: '1'
proxy_auth:
  enabled: true
  api_key: "your-secure-api-key"
servers:
  fetch:
    image: mcp/fetch
    runtime: docker
    protocol: stdio
    capabilities: [tools]
    networks: [mcp-net]
```

And got this error
```
Errors encountered:
- Server 'fetch' failed to start: failed to start container for server 'fetch': no container runtime available, cannot start container with image 'mcp/fetch'
```

I'm in a distrobox environment so it's podman under the hood but I don't have a `podman` cli, but I do have a `docker` cli. I tried setting the runtime to `podman` in case that helped. Same error either way.
